Repository team-xquare/v1-service-notification, pull requests merged in 2023-05, with the labels that each got.

#217 🔀 :: (#20) 알림 목록 조회시 읽음처리
  notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/NotificationDetailApiImpl.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/PostDetailRepositorySpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/CustomDetailRepositoryImpl.kt
Labels: chore

#218 🔀 :: (#21) InmemoryRepository 테스트 수정
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryCategoryRepository.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt
  notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/DetailApiImplTest.kt
Labels: 버그

#219 🔀 :: (#49) sql 500에러 해결 & time zone 변경
  Dockerfile
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
Labels: 리팩토링

#220 🔀 :: (#26) 리스트 날짜 내림차순으로 정렬
  notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/NotificationDetailApiImpl.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/QueryDetailRepositorySpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt
  notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/DetailApiImplTest.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/CustomDetailRepositoryImpl.kt
Labels: chore

#221 🔀 :: (#79) 그룹알림 devicetoken length 제한 추가
  notification-domain/src/main/kotlin/io/github/v1servicenotification/error/ErrorCode.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/error/InvalidDeviceTokenLengthException.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmService.kt
Labels: 버그

#223 🔀 :: (#94) codeowners 수정
  .github/CODEOWNERS
Labels: chore

#222 🔀 :: (#80) 4096 Bytes Error 해결
  notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/PostDetailUserSpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryUser.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/user/domain/repository/CustomPostDetailUserImpl.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/UserClient.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/dto/request/ExcludeUserIdsRequest.kt
Labels: 버그

#225 🔀 :: (#71) 알림 카테고리 활성화 / 비활성화 변경
  notification-domain/src/main/kotlin/io/github/v1servicenotification/error/ErrorCode.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/api/SettingApi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/exception/SettingNotFoundException.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/spi/SettingCategorySpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/spi/SettingRepositorySpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryCategoryRepository.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt
  notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/DetailApiImplTest.kt
  notification-domain/src/test/kotlin/io/github/v1servicenotification/setting/SettingApiImplTest.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/CustomCategoryRepositoryImpl.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/presentation/SettingController.kt
Labels: 리팩토링

#224 🔀 :: (#103) 활성화된 알림 카테고리 목록 api 변경
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/api/SettingApi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/api/response/SettingElement.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/api/response/SettingListResponse.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/spi/SettingRepositorySpi.kt
  notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt
  notification-domain/src/test/kotlin/io/github/v1servicenotification/setting/SettingApiImplTest.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
  notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/presentation/SettingController.kt
Labels: 리팩토링
